### PR TITLE
Move transparency-obligation-organization to a separate folder

### PR DESCRIPTION
**Pull request by simonetw**

### CODE REVIEW

**Comment by giorgialodi** [comment]
As I said in other messaging system, probably this does not make sense. The controlled vocabulary of reference is transparency-obligation. This is not a controlled voc per sé. It is just a set of additional triples for the main voc that is transparency-obligation.

**Comment by ioggstream** [comment]
@giorgialodi if it does not break anything, I will approve and move on.

**Review by giorgialodi — CHANGES_REQUESTED** [review]
I think this PR should be deleted.

**Comment by giorgialodi** [comment]
@bfabio @mfortini cancellerei questa PR come scritto sopra.

**Pull request closed without merging**
