### PR TITLE
refactor: use a symlink for latest version

### PR DESCRIPTION
**Pull request by bfabio**
This commit applies only to ontologies where the latest directory is identical to the latest versioned directory. There are still some ontologies where this is not the case, and they need to be fixed

See #107.

### CODE REVIEW

**Comment by giorgialodi** [comment]
ok @bfabio I will have a look at the rest. In the meantime I will approve this.

**Review by giorgialodi — APPROVED** [review]

**Comment by ioggstream** [comment]
@bfabio are symlinks compatible with raw.githubusercontent.com/.... ?

**Comment by ioggstream** [comment]
Another way could be to always copy the latest directory to latest/ via the CI, or to design a way to publish files via gh-pages instead of using raw.ghuc.com

Wdyt?

**Comment by bfabio** [comment]
Potentially obsoleted by #269.

**Pull request closed without merging**
